version: 2.1

defaults: &defaults
  working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
  docker:
    - image: circleci/golang:1.13

commands:
  install:
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependancy-cache-{{checksum "go.sum"}}
            - dependancy-cache-
      - run: go get -v -t -d ./...
      - save_cache:
          key: dependancy-cache-{{checksum "go.sum"}}
          paths:
            - /go/src/
      - run:
          name: Check prices
          command: |
            go run main.go

jobs:
  pricing:
    <<: *defaults
    steps:
      - install
      - run: go run main.go

poll:
  triggers:
    - schedule:
      # Every 3 hour
      cron: "0 * * * *"
      filters:
        branches:
        only:
          - master
  jobs:
    - pricing:
        filters:
          branches:
            only:
              - master
