version: 2.1

defaults: &defaults
  working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
  docker:
    - image: circleci/golang:1.13

commands:
  install:
    steps:
      - checkout
      - run: go get -v -t -d ./...
  check_price:
    steps:
      - checkout
      - run: go run main.go

jobs:
  pricing:
    <<: *defaults
    steps:
      - install
      - check_price

workflows:
  version: 2

  test:
    jobs:
      - pricing:
          filters:
            branches:
              only:
                - master

    poll:
      triggers:
        - schedule:
        # Every 3 hour
            cron: "0 * * * *"
            filters:
              branches:
                only:
                  - master
      jobs:
        - pricing:
            filters:
              branches:
                only:
                  - master
