version: 2.1

defaults: &defaults
#   working_directory: /go/src/github.com/{{CIRCLE_PROJECT_USERNAME}}/{{CIRCLE_PROJECT_REPONAME}}
  docker:
    - image: circleci/golang:1.13

commands:
  install:
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go get -v -t -d ./...
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  check_price:
    steps:
      - checkout
      - run: go run main.go

jobs:
  pricing:
    <<: *defaults
    steps:
      - install
      - check_price

workflows:
  version: 2
  poll:
    triggers:
      - schedule:
          # Every day at 12PM
          cron: "0 12 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - pricing:
          filters:
            branches:
              only:
                - master
